// Mock Data for SceneLink

// Available interests for user selection
const AVAILABLE_INTERESTS = [
  { id: 'musik', name: 'Music', icon: '🎵' },
  { id: 'konzerte', name: 'Concerts', icon: '🎤' },
  { id: 'kunst', name: 'Art', icon: '🎨' },
  { id: 'sport', name: 'Sports', icon: '⚽' },
  { id: 'yoga', name: 'Yoga', icon: '🧘' },
  { id: 'food', name: 'Food & Culinary', icon: '🍕' },
  { id: 'party', name: 'Party & Nightlife', icon: '🎉' },
  { id: 'kultur', name: 'Culture', icon: '🎭' },
  { id: 'outdoor', name: 'Outdoor & Nature', icon: '🌲' },
  { id: 'fotografie', name: 'Photography', icon: '📸' },
  { id: 'workshops', name: 'Workshops', icon: '🛠️' },
  { id: 'networking', name: 'Networking', icon: '🤝' },
  { id: 'nachhaltigkeit', name: 'Sustainability', icon: '♻️' },
  { id: 'techno', name: 'Techno', icon: '🎧' },
  { id: 'indie', name: 'Indie', icon: '🎸' }
];

// Event categories for filtering
const EVENT_CATEGORIES = [
  { id: 'all', name: 'All Events', icon: '🔍' },
  { id: 'konzert', name: 'Concerts', icon: '🎤' },
  { id: 'kunst', name: 'Art & Culture', icon: '🎨' },
  { id: 'sport', name: 'Sports & Wellness', icon: '⚽' },
  { id: 'food', name: 'Food & Drink', icon: '🍕' },
  { id: 'party', name: 'Party', icon: '🎉' },
  { id: 'workshop', name: 'Workshops', icon: '🛠️' },
  { id: 'outdoor', name: 'Outdoor', icon: '🌲' },
  { id: 'community', name: 'Community & Sustainable', icon: '♻️' }
];

const MOCK_EVENTS = [
  {
    id: 1,
    title: "Summer Jazz Night",
    type: "Concert",
    category: "konzert",
    date: "2026-01-15",
    time: "20:00",
    location: "Blue Note Club",
    city: "Köln",
    distance: "2 km",
    lat: 52.5200,
    lng: 13.4050,
    image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&h=1000&fit=crop",
    attendees: 45,
    goingSolo: 12,
    description: "An unforgettable evening mit den besten Jazz-Künstlern der Stadt. Live music, great atmosphere, and meet new people!",
    price: "15€",
    tags: ["Music", "Jazz", "Live"],
    interests: ["musik", "konzerte"],
    isSustainable: false,
    hasTickets: true,
    ticketUrl: "#"
  },
  {
    id: 2,
    title: "Street Art Workshop",
    type: "Art & Culture",
    category: "kunst",
    date: "2026-01-18",
    time: "14:00",
    location: "Urban Art Space",
    city: "Köln",
    distance: "1.5 km",
    lat: 52.5100,
    lng: 13.4150,
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&h=1000&fit=crop",
    attendees: 28,
    goingSolo: 8,
    description: "Learn the basics der Street Art von professionellen Künstlern. Perfekt für Anfänger und Fortgeschrittene!",
    price: "Kostenlos",
    tags: ["Art", "Workshop", "Creative"],
    interests: ["kunst", "workshops"],
    isSustainable: false,
    hasTickets: false
  },
  {
    id: 3,
    title: "Rooftop Yoga Session",
    type: "Sports & Wellness",
    category: "sport",
    date: "2026-01-20",
    time: "07:00",
    location: "SkyHigh Yoga Studio",
    city: "Köln",
    distance: "3 km",
    lat: 52.5250,
    lng: 13.3900,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=1000&fit=crop",
    attendees: 32,
    goingSolo: 15,
    description: "Starte deinen Tag mit Yoga auf dem Dach mit atemberaubendem Stadtblick. Alle Level willkommen!",
    price: "12€",
    tags: ["Sport", "Yoga", "Wellness"],
    interests: ["yoga", "sport", "outdoor"],
    isSustainable: false,
    hasTickets: true,
    ticketUrl: "#"
  },
  {
    id: 4,
    title: "Food Market Festival",
    type: "Food & Drink",
    category: "food",
    date: "2026-01-22",
    time: "12:00",
    location: "Markthalle Neun",
    city: "Köln",
    distance: "4 km",
    lat: 52.4950,
    lng: 13.4250,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=1000&fit=crop",
    attendees: 120,
    goingSolo: 35,
    description: "Die besten Street Food Stände der Stadt an einem Ort. Genieße internationale Küche und tolle Musik!",
    price: "Eintritt frei",
    tags: ["Food", "Festival", "Culinary"],
    interests: ["food", "musik"],
    isSustainable: false,
    hasTickets: false
  },
  {
    id: 5,
    title: "Indie Rock Concert",
    type: "Concert",
    category: "konzert",
    date: "2026-01-25",
    time: "21:00",
    location: "Lido Köln",
    city: "Köln",
    distance: "2.8 km",
    lat: 52.5150,
    lng: 13.4100,
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=1000&fit=crop",
    attendees: 85,
    goingSolo: 22,
    description: "Die angesagtesten Indie Bands live auf der Bühne. Eine Nacht voller guter Musik und neuer Bekanntschaften!",
    price: "22€",
    tags: ["Music", "Indie", "Rock"],
    interests: ["musik", "indie", "konzerte"],
    isSustainable: false,
    hasTickets: true,
    ticketUrl: "#"
  },
  {
    id: 6,
    title: "Photography Walk",
    type: "Photography",
    category: "outdoor",
    date: "2026-01-28",
    time: "10:00",
    location: "Treffpunkt: Alexanderplatz",
    city: "Köln",
    distance: "1 km",
    lat: 52.5219,
    lng: 13.4132,
    image: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&h=1000&fit=crop",
    attendees: 18,
    goingSolo: 9,
    description: "Entdecke die Stadt durch deine Linse. Gemeinsamer Fotospaziergang durch die interessantesten Viertel Kölns.",
    price: "Kostenlos",
    tags: ["Photography", "Outdoor", "Creative"],
    interests: ["fotografie", "outdoor"],
    isSustainable: false,
    hasTickets: false
  },
  {
    id: 7,
    title: "Techno Open Air",
    type: "Party",
    category: "party",
    date: "2026-02-01",
    time: "16:00",
    location: "Tempelhofer Feld",
    city: "Köln",
    distance: "5 km",
    lat: 52.4730,
    lng: 13.4050,
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&h=1000&fit=crop",
    attendees: 200,
    goingSolo: 58,
    description: "Das größte Open Air Techno Event des Sommers! Top DJs, tolle Vibes und unvergessliche Momente.",
    price: "25€",
    tags: ["Party", "Techno", "Open Air"],
    interests: ["party", "techno", "musik"],
    isSustainable: false,
    hasTickets: true,
    ticketUrl: "#"
  },
  {
    id: 8,
    title: "Book Club Meetup",
    type: "Culture",
    category: "kultur",
    date: "2026-02-05",
    time: "18:30",
    location: "Café Literatour",
    city: "Köln",
    distance: "2.2 km",
    lat: 52.5080,
    lng: 13.4020,
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&h=1000&fit=crop",
    attendees: 15,
    goingSolo: 7,
    description: "Monatliches Treffen für Buchliebhaber. Diskutiere über aktuelle Bestseller und klassische Literatur.",
    price: "Kostenlos",
    tags: ["Books", "Culture", "Networking"],
    interests: ["kultur", "networking"],
    isSustainable: false,
    hasTickets: false
  },
  {
    id: 9,
    title: "Food Waste Cooking Class",
    type: "Workshop",
    category: "community",
    date: "2026-01-19",
    time: "17:00",
    location: "Green Kitchen Studio",
    city: "Köln",
    distance: "2.5 km",
    lat: 52.5180,
    lng: 13.3980,
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=1000&fit=crop",
    attendees: 22,
    goingSolo: 11,
    description: "Lerne kreative Rezepte mit geretteten Lebensmitteln! Gemeinsam kochen wir ein 3-Gänge-Menü und setzen ein Zeichen gegen Verschwendung.",
    price: "18€",
    tags: ["Food", "Sustainability", "Workshop"],
    interests: ["food", "nachhaltigkeit", "workshops"],
    isSustainable: true,
    sustainabilityType: "Food Waste Prevention",
    hasTickets: true,
    ticketUrl: "#"
  },
  {
    id: 10,
    title: "Second-Hand Fashion Swap",
    type: "Community Event",
    category: "community",
    date: "2026-01-23",
    time: "14:00",
    location: "Community Hall Kreuzberg",
    city: "Köln",
    distance: "3.2 km",
    lat: 52.4990,
    lng: 13.4150,
    image: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&h=1000&fit=crop",
    attendees: 45,
    goingSolo: 18,
    description: "Tausche deine alten Lieblingsstücke gegen neue Schätze! Bring bis zu 5 Kleidungsstücke und finde neue Styles. Für jeden Tausch spenden wir an lokale Hilfsorganisationen.",
    price: "5€ Spende",
    tags: ["Fashion", "Sustainability", "Community"],
    interests: ["nachhaltigkeit", "networking"],
    isSustainable: true,
    sustainabilityType: "Circular Economy",
    hasTickets: true,
    ticketUrl: "#"
  },
  {
    id: 11,
    title: "Urban Gardening Workshop",
    type: "Workshop",
    category: "community",
    date: "2026-01-26",
    time: "10:00",
    location: "Prinzessinnengarten",
    city: "Köln",
    distance: "3.8 km",
    lat: 52.5070,
    lng: 13.4110,
    image: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&h=1000&fit=crop",
    attendees: 30,
    goingSolo: 14,
    description: "Lerne die Basics des urbanen Gärtnerns! Wir bauen gemeinsam Hochbeete, säen Gemüse und schaffen grüne Oasen in der Stadt.",
    price: "12€",
    tags: ["Nature", "Sustainability", "Workshop"],
    interests: ["nachhaltigkeit", "outdoor", "workshops"],
    isSustainable: true,
    sustainabilityType: "Urban Sustainability",
    hasTickets: true,
    ticketUrl: "#"
  },
  {
    id: 12,
    title: "Newcomers Welcome Meetup",
    type: "Networking",
    category: "community",
    date: "2026-01-21",
    time: "19:00",
    location: "Köln Welcome Center",
    city: "Köln",
    distance: "1.8 km",
    lat: 52.5230,
    lng: 13.4070,
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=1000&fit=crop",
    attendees: 65,
    goingSolo: 42,
    description: "Neu in Köln? Triff andere Newcomer und Locals die dir die Stadt zeigen! Mit Drinks, Snacks und Speed-Networking zum Leute kennenlernen.",
    price: "Kostenlos",
    tags: ["Networking", "Newcomers", "Community"],
    interests: ["networking"],
    isSustainable: false,
    hasTickets: false,
    isNewcomerEvent: true
  }
];

const MOCK_USERS = [
  {
    id: 1,
    name: "Sarah",
    age: 26,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    interests: ["konzerte", "kunst", "food"],
    bio: "Music lover & Foodie",
    isNewcomer: true,
    movedToCity: "2023-08",
    cityOrigin: "Cologne"
  },
  {
    id: 2,
    name: "Tom",
    age: 28,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tom",
    interests: ["sport", "outdoor", "fotografie"],
    bio: "Always on the go, looking for the perfect shot",
    isNewcomer: false
  },
  {
    id: 3,
    name: "Lisa",
    age: 24,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    interests: ["party", "techno", "musik"],
    bio: "Techno is life 🎵",
    isNewcomer: false
  },
  {
    id: 4,
    name: "Jonas",
    age: 30,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jonas",
    interests: ["kultur", "networking", "musik"],
    bio: "Bookworm & Jazz enthusiast",
    isNewcomer: true,
    movedToCity: "2024-01",
    cityOrigin: "Düsseldorf"
  },
  {
    id: 5,
    name: "Emma",
    age: 25,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    interests: ["yoga", "nachhaltigkeit", "outdoor"],
    bio: "Namaste 🧘‍♀️",
    isNewcomer: false
  },
  {
    id: 6,
    name: "Felix",
    age: 27,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix",
    interests: ["indie", "musik", "konzerte"],
    bio: "Festival Season is the best season",
    isNewcomer: false
  },
  {
    id: 7,
    name: "Nina",
    age: 23,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nina",
    interests: ["kunst", "kultur", "fotografie"],
    bio: "Art lover",
    isNewcomer: true,
    movedToCity: "2023-11",
    cityOrigin: "Cologne"
  },
  {
    id: 8,
    name: "Max",
    age: 29,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Max",
    interests: ["food", "nachhaltigkeit"],
    bio: "Foodie 🍕",
    isNewcomer: false
  }
];

const MOCK_MATCHES = [
  {
    id: 1,
    user: MOCK_USERS[0],
    event: MOCK_EVENTS[0],
    matchDate: "2024-06-10",
    isNew: true,
    lastMessage: "Hey! Are you excited for the jazz concert? 🎵",
    messageTime: "2 hours ago",
    commonInterests: ["konzerte", "musik"]
  },
  {
    id: 2,
    user: MOCK_USERS[1],
    event: MOCK_EVENTS[2],
    matchDate: "2024-06-09",
    isNew: true,
    lastMessage: "Have you been to rooftop yoga before?",
    messageTime: "5 hours ago",
    commonInterests: ["sport", "outdoor"]
  },
  {
    id: 3,
    user: MOCK_USERS[2],
    event: MOCK_EVENTS[6],
    matchDate: "2024-06-08",
    isNew: true,
    lastMessage: "The open air will be amazing! 🔥",
    messageTime: "Yesterday",
    commonInterests: ["party", "techno", "musik"]
  },
  {
    id: 4,
    user: MOCK_USERS[3],
    event: MOCK_EVENTS[7],
    matchDate: "2024-06-07",
    isNew: false,
    lastMessage: "What book are you reading right now?",
    messageTime: "2 days ago",
    commonInterests: ["kultur", "networking"]
  },
  {
    id: 5,
    user: MOCK_USERS[4],
    event: MOCK_EVENTS[2],
    matchDate: "2024-06-06",
    isNew: false,
    lastMessage: "I'll bring my own mat!",
    messageTime: "3 days ago",
    commonInterests: ["yoga"]
  },
  {
    id: 6,
    user: MOCK_USERS[5],
    event: MOCK_EVENTS[4],
    matchDate: "2024-06-05",
    isNew: false,
    lastMessage: "Do you know the band already?",
    messageTime: "4 days ago",
    commonInterests: ["indie", "konzerte"]
  },
  {
    id: 7,
    user: MOCK_USERS[6],
    event: MOCK_EVENTS[1],
    matchDate: "2024-06-04",
    isNew: false,
    lastMessage: "Do you have experience with graffiti?",
    messageTime: "5 days ago",
    commonInterests: ["kunst"]
  },
  {
    id: 8,
    user: MOCK_USERS[7],
    event: MOCK_EVENTS[3],
    matchDate: "2024-06-03",
    isNew: false,
    lastMessage: "I can recommend the Asian stalls!",
    messageTime: "1 week ago",
    commonInterests: ["food"]
  }
];

// User's liked events (for profile view)
const LIKED_EVENTS = [1, 3, 4, 6, 9, 12];

// Current user profile (would normally come from authentication)
let CURRENT_USER = {
  id: 999,
  name: "",
  age: 24,
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user",
  bio: "",
  interests: [], // Will be set during onboarding
  isNewcomer: false,
  hasCompletedOnboarding: false,
  matchPreferences: {
    ageMin: 18,
    ageMax: 35,
    peopleType: 'open', // 'open', 'newcomers', 'locals'
    vibe: 'chill' // 'chill', 'active', 'party'
  }
};
